### ISSUE TITLE
pretty printing output during development

### ISSUE THREAD

**Issue by ruffrey** [rvagg/bole#13]
Great fast library..are you using another tool to format the logs during development? If not, is there a hidden option for formatting the output like `JSON.stringify(object, null, 2)`?

**Comment by ruffrey** [comment]
P.S. I tried running it through the bunyan CLI, but that did not want to format it, for some reason.

**Comment by yoshuawuyts** [comment]
I tend to use [garnish](https://github.com/mattdesl/garnish); perhaps you'll find that one to your liking. Cheers!

**Comment by ruffrey** [comment]
@yoshuawuyts garnish is PERFECT. Thanks very much ✅

**Comment by rvagg** [comment]
There's also  https://github.com/hughsk/bistre

we really should list these on the README
