### ISSUE TITLE
How to disable logging from sub modules, but keep logging from the "top level" app

### ISSUE THREAD

**Issue by alexindigo** [rvagg/bole#17]
I have several modules that use bole for logging and one of them is very chatty (on `info` level),
so it would be nice to have ability to filter output stream based on log names, so I can have separate file with app's only logs.

Is it something that could be done in the existing version?

Thank you.

**Comment by rvagg** [comment]
sorry about not responding to this earlier @alexindigo 
I think the answer to this is probably _no_, but you could do it if you wanted to inspect the output, either JSON parsing or crossing your fingers and matching `"level":"info"` or similar.
If this is something someone wants to try and tackle then I'd entertain a PR, I'd just be on the lookout for significant increases in complexity and decreases in performance. bole was intended to be simple and fast.

**Comment by alexindigo** [comment]
Oh, this is an old one, let it rest in peace :)
