### ISSUE TITLE
Use of os.hostname() causes runtime crash on Wndows 7

### ISSUE THREAD

**Issue by zhanglolo** [rvagg/bole#20]
hello, when i use pnpm on win7, i got an error, then i find there error stack point to 

https://github.com/rvagg/bole/blob/9929b9e2abc508d574e8f0081a275b4925533776/bole.js#L7

the cause reason  is  https://github.com/ericelliott/cuid/issues/263

hope it can be fixed 🙏

**Comment by rvagg** [comment]
What is the effect on win7? Does the process crash or does it throw an error with a stacktrace? Would it work to wrap this in a try/catch and then follow up with the https://github.com/ericelliott/cuid/issues/263 solution in the catch? I'd rather not ignore a hostname if it's there to be used, but if it's a fatal process-crash then maybe that's not even possible. Can you paste some error output of this running on your win7?

**Comment by zhanglolo** [comment]
### here is infomation:
- NodeJS 16.16.0
- Windows 7
- pnpm 7.9.0

> Because the computer is on the intranet, I can't take screenshots and can only take pictures.

run `pnpm config list` in CMD:
![IMG_2557](https://user-images.githubusercontent.com/27875371/183839467-ed5fedaf-fc8f-4b14-99a8-6c703f11f7a3.JPG)

pnpm dist, line 9177:
![IMG_2559](https://user-images.githubusercontent.com/27875371/183839892-b14327c5-974f-4b67-b853-eb930aff4846.JPG)

I modified `var hostname = require("os").hostname()` to `var hostname = require("os").version().indexOf('Windows 7 ') === 0 ? 'windows7' : os.hostname()`  as a temporary solution.
pnpm run correctly.

**Comment by rvagg** [comment]
ok, so that doesn't look like a fatal, it's being captured by the exception system, we could feature-detect that. Would you mind submitting a pull request with a change for this? Something like:

```js
const os = require('os')
var hostname
try {
  hostname = os.hostname()
} catch (e) {
  if (os.version().indexOf('Windows 7 ') === 0) {
    hostname = 'windows7'
  } else {
    throw e
  }
}
```

You could try that code out locally in your pnpm install to make sure it works properly first.

**Comment by zhanglolo** [comment]
`pnpm` dependent on `@pnpm/logger`, and  `@pnpm/logger` dependent on `bole`:

https://github.com/pnpm/logger/blob/d9e12c10a591ebb6e21ce2a06464ec04bbccdb08/package.json#L39

---

```
const os = require('os')
var hostname
try {
  hostname = os.hostname()
} catch (e) {
  if (os.version().indexOf('Windows 7 ') === 0) {
    hostname = 'windows7'
  } else {
    throw e
  }
}
```
it works.  
but i think throw error again may cause some problem. 
If package who use `bole`  forgot handle error, win7 user may get some error.

I don't  konw  how `@pnpm/logger` use the `hostname`.  
May be return a special characters to indicate that the hostname cannot be obtained?

**Comment by rvagg** [comment]
yeah, you might be right actually, this piece of information is usually pretty low utility so we could just insert something:

```js
} catch (e) {
  hostname = os.version().indexOf('Windows 7 ') === 0 ?  'windows7' : 'hostname-unknown'
}
```

**Comment by zhanglolo** [comment]
I think this ok.  Will you publish a version like 4.0.1 or 4.1.0 on npm ? 
I will notify `@pnpm/logger` author to update `bole`。

**Comment by rvagg** [comment]
I'll publish a 4.0.1, but would you mind doing a pull request here with the change?
