### ISSUE TITLE
What's the right way to log nested objects to stdout?

### ISSUE THREAD

**Issue by vivekprm** [rvagg/bole#30]
I was trying to log some objects using 
`logger.debug("data is", dataObj);`

However some objects are not getting logged properly, instead of expanded object I am seeing just "Object":
`headers: {\n    host: [ [Object] ],\n    'user-agent': [ [Object] ],\n    accept: [ [Object] ]\n  }`

Here is my bole config:
`bole.output({
  level: process.env.LOG_LEVEL || 'debug',
  stream: process.stdout
});`

What is the right way to log nested objects in stdout. I don't want to log stringified objects.

**Comment by rvagg** [comment]
bole isn't intended to format anything more complex than key:scalar values, key:object or key:array is going to end up in a situation like this -- my suggestion would be to flatten your objects if you have more complex things to log; or alternatively to find a logger that supports more complex logging options; bole isn't really "fully featured", it's meant to be simple and fast

I hope that helps

**Comment by vivekprm** [comment]
Ok thanks...make sense
