### ISSUE TITLE
ability to only have explicit levels logged

### ISSUE THREAD

**Issue by ckross01** [rvagg/bole#6]
it would be nice to be able to specify explicit levels for logging. So instead of info getting that and the levels above it would be cool to allow for only info, warn, debug to be printed out.

**Comment by yoshuawuyts** [comment]
Am I right in assuming this is for debugging purposes? You could achieve the same effect by using `grep`. E.g. (hope I got the escaping right):
```sh
node app.js | grep '"level":"info"'

**Comment by ckross01** [comment]
good point with just using grep, and yes the escaping was correct. My main use case was that I was thinking it would be nice to only log warnings to fs (as an example) and not get both warnings and errors.  Or any log level for that matter.

but thinking about it might be better to have my log aggregator control that workflow.

thanks
