### ISSUE TITLE
perf improvements

### ISSUE THREAD

**Issue by yoshuawuyts** [rvagg/bole#8]
There's a [new kid on the block](https://github.com/mcollina/pino) and things aren't looking too great for `bole` perf-wise.

```txt
benchBunyanObj*10000: 1252.539ms
benchWinstonObj*10000: 1729.837ms
benchBoleObj*10000: 1491.677ms
benchPinoObj*10000: 365.207ms
```

Perhaps it'd be good to find out where `bole`'s pain points lie and see if we can speed things up a bit. `pino` uses the following packages that were built specifically for it:
- [quick-format](https://www.npmjs.com/package/quick-format) - fast `util.format` replacement
- [fast-safe-stringify](https://www.npmjs.com/package/fast-safe-stringify) - fast and safe `JSON.stringify` implementation

**Comment by rvagg** [comment]
:boom: v3 is out
